server:
  port: 2766
  servlet:
      encoding:
        force: true
        charset: UTF-8
        enabled: true
  tomcat:
      uri-encoding: UTF-8

spring:
  servlet:
    multipart:
      max-file-size: 1GB
      max-request-size: 1GB
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.109.22.92:3306/game_community?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    username: game_community
    password: 6KDLnpsTj5NmDKaB
  rabbitmq:
    host: 47.109.22.92
    port: 5672
    username: abyss
    password: rabbitmq123456789
    virtual-host: /
    publisher-returns: true
    listener:
      # Routing 路由模型（交换机类型：direct）
      direct:
        #消息确认：手动签收
        acknowledge-mode: manual
        #当前监听容器数
        concurrency: 1
        #最大数
        max-concurrency: 10
        #是否支持重试
        retry:
          enabled: true
          #重试次数5,超过5次抛出异常
          max-attempts: 5
          #重试间隔 3s
          max-interval: 3000




  data:
    redis:
      host: 47.109.22.92
      port: 6379
      password: AbyssRedis
      lettuce:
        pool:
          max-active: 8
          max-wait:  -1
          min-idle: 0
